export const TOPICS = [
  'Abstract Painting',
  'Adventure Micro-Escapes',
  'Aerial Earth',
  'Coastal Surf Vibes',
  'Minimalist Zen Spaces',
  'Wild Textures',
  'Vintage Trains',
  'Amsterdam Urban',
  'Minimalist Wallpaper',
  'Fresh & Seasonal Food Flat-lays',
  'Neon Tokyo Nights',
  'Nordic Hygge Interiors',
  'Carnival Pop Colours',
  'Smart Home Tech',
  'Thai Temple Serenity',
];
