name: CI

on:
  pull_request:
    # Trigger CI only when a pull request targets the `main` branch
    branches: [main]
  push:
    # Also trigger CI when pushing directly to the main branch
    branches: [main]

# Cancel previously running workflow for the same PR branch
concurrency:
  group: ci-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  validate:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: 🧹 Lint
            command: lint
          - name: 🧪 Test
            command: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.10.0

      # Node.js with pnpm caching
      - name: Set up Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Run the command based on matrix
      - name: Run ${{ matrix.command }}
        run: pnpm run ${{ matrix.command }}
